runtime: php73 # Replace with php74 to use PHP 7.4

handlers:
  - url: /css
    static_dir: public/css
  - url: /js
    static_dir: public/js
  - url: /img
    static_dir: public/img

# Serve your app through a front controller at index.php or public/index.php.
  - url: .*
    script: auto

env_variables:
  APP_KEY: base64:lHBHVaJ/bTozwFaUtdaX/R8f9Avc7+8dXKQDsrukS2E=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
    ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: model_seeker_db
  DB_USERNAME: ugkajiwara
  DB_PASSWORD: y0u3j1i0ms

  LOG_CHANNEL: stackdriver

  DB_SOCKET: /cloudsql/model-seeker:asia-northeast1:model-seeker-database

  # # add 7/26 1:13
  # MYSQL_USER: ugkajiwara
  # MYSQL_PASSWORD: y0u3j1i0ms
  # MYSQL_DSN: mysql:dbname=DATABASE;unix_socket=/cloudsql/model-seeker:asia-northeast1:model-seeker-database

beta_settings:
  cloud_sql_instances: model-seeker:asia-northeast1:model-seeker-database